/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 28
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__newline = 1,
  sym_separator = 2,
  sym_comment = 3,
  anon_sym_EQ = 4,
  sym_variable_name = 5,
  sym_method = 6,
  aux_sym_url_token1 = 7,
  anon_sym_LBRACE = 8,
  sym_version = 9,
  sym_header_name = 10,
  sym_text = 11,
  sym_variable = 12,
  sym_document = 13,
  sym__line = 14,
  sym_variable_declaration = 15,
  sym_request_line = 16,
  sym_url = 17,
  sym_header = 18,
  sym_body_line = 19,
  aux_sym__text = 20,
  aux_sym_document_repeat1 = 21,
  aux_sym_url_repeat1 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__newline] = "_newline",
  [sym_separator] = "separator",
  [sym_comment] = "comment",
  [anon_sym_EQ] = "=",
  [sym_variable_name] = "variable_name",
  [sym_method] = "method",
  [aux_sym_url_token1] = "url_token1",
  [anon_sym_LBRACE] = "{",
  [sym_version] = "version",
  [sym_header_name] = "header_name",
  [sym_text] = "text",
  [sym_variable] = "variable",
  [sym_document] = "document",
  [sym__line] = "_line",
  [sym_variable_declaration] = "variable_declaration",
  [sym_request_line] = "request_line",
  [sym_url] = "url",
  [sym_header] = "header",
  [sym_body_line] = "body_line",
  [aux_sym__text] = "_text",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_url_repeat1] = "url_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__newline] = sym__newline,
  [sym_separator] = sym_separator,
  [sym_comment] = sym_comment,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_variable_name] = sym_variable_name,
  [sym_method] = sym_method,
  [aux_sym_url_token1] = aux_sym_url_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [sym_version] = sym_version,
  [sym_header_name] = sym_header_name,
  [sym_text] = sym_text,
  [sym_variable] = sym_variable,
  [sym_document] = sym_document,
  [sym__line] = sym__line,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_request_line] = sym_request_line,
  [sym_url] = sym_url,
  [sym_header] = sym_header,
  [sym_body_line] = sym_body_line,
  [aux_sym__text] = aux_sym__text,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_url_repeat1] = aux_sym_url_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_variable_name] = {
    .visible = true,
    .named = true,
  },
  [sym_method] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_url_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_version] = {
    .visible = true,
    .named = true,
  },
  [sym_header_name] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_request_line] = {
    .visible = true,
    .named = true,
  },
  [sym_url] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_body_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__text] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_url_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_method = 1,
  field_name = 2,
  field_url = 3,
  field_value = 4,
  field_version = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_method] = "method",
  [field_name] = "name",
  [field_url] = "url",
  [field_value] = "value",
  [field_version] = "version",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_method, 0},
    {field_url, 1},
  [3] =
    {field_name, 0},
    {field_value, 1},
  [5] =
    {field_name, 0},
    {field_value, 2},
  [7] =
    {field_method, 0},
    {field_url, 1},
    {field_version, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 12,
  [15] = 11,
  [16] = 10,
  [17] = 7,
  [18] = 13,
  [19] = 8,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 24,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(44);
      ADVANCE_MAP(
        '\n', 45,
        '\r', 1,
        '#', 50,
        '/', 2,
        '=', 54,
        '@', 40,
        'C', 23,
        'D', 11,
        'G', 12,
        'H', 13,
        'O', 26,
        'P', 6,
        'T', 27,
        '{', 63,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(45);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(53);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(39);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'A') ADVANCE(10);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'A') ADVANCE(9);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'A') ADVANCE(32);
      if (lookahead == 'O') ADVANCE(28);
      if (lookahead == 'U') ADVANCE(30);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'C') ADVANCE(30);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'C') ADVANCE(17);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'C') ADVANCE(14);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'D') ADVANCE(56);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'E') ADVANCE(19);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 12:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'E') ADVANCE(30);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 13:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'E') ADVANCE(4);
      if (lookahead == 'T') ADVANCE(33);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 14:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'E') ADVANCE(56);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 15:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'E') ADVANCE(7);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 16:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'E') ADVANCE(34);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 17:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'H') ADVANCE(56);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 18:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'I') ADVANCE(24);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 19:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'L') ADVANCE(16);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 20:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'N') ADVANCE(22);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 21:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'N') ADVANCE(29);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 22:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'N') ADVANCE(15);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 23:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'O') ADVANCE(20);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 24:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'O') ADVANCE(21);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 25:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'P') ADVANCE(3);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 26:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'P') ADVANCE(31);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 27:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'R') ADVANCE(5);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 28:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'S') ADVANCE(30);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 29:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'S') ADVANCE(56);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 30:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'T') ADVANCE(56);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 31:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'T') ADVANCE(18);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 32:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'T') ADVANCE(8);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 33:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'T') ADVANCE(25);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 34:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'T') ADVANCE(14);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 35:
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 36:
      if (lookahead == '{') ADVANCE(63);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(62);
      END_STATE();
    case 37:
      if (lookahead == '}') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(37);
      END_STATE();
    case 38:
      if (lookahead == '}') ADVANCE(102);
      END_STATE();
    case 39:
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 40:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 41:
      if (eof) ADVANCE(44);
      ADVANCE_MAP(
        '\n', 45,
        '\r', 1,
        '#', 51,
        '/', 68,
        '@', 100,
        'C', 88,
        'D', 77,
        'G', 78,
        'H', 79,
        'O', 90,
        'P', 71,
        'T', 91,
        '{', 99,
        '\t', 66,
        ' ', 66,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0) ADVANCE(101);
      END_STATE();
    case 42:
      if (eof) ADVANCE(44);
      if (lookahead == '\n') ADVANCE(45);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'H') ADVANCE(60);
      if (lookahead == '{') ADVANCE(63);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(42);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(62);
      END_STATE();
    case 43:
      if (eof) ADVANCE(44);
      if (lookahead == '\n') ADVANCE(45);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '{') ADVANCE(99);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead != 0) ADVANCE(101);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_separator);
      if (lookahead == '{') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_separator);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '#') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(53);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '#') ADVANCE(46);
      if (lookahead == '{') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(52);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '#') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(53);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '#') ADVANCE(49);
      if (lookahead == '{') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '{') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_variable_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_method);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_url_token1);
      if (lookahead == '/') ADVANCE(61);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(62);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_url_token1);
      if (lookahead == 'P') ADVANCE(57);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(62);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_url_token1);
      if (lookahead == 'T') ADVANCE(58);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(62);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_url_token1);
      if (lookahead == 'T') ADVANCE(59);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(62);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_url_token1);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_url_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{') ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '{') ADVANCE(37);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_version);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_header_name);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_text);
      ADVANCE_MAP(
        '\n', 45,
        '\r', 1,
        '#', 51,
        '/', 68,
        '@', 100,
        'C', 88,
        'D', 77,
        'G', 78,
        'H', 79,
        'O', 90,
        'P', 71,
        'T', 91,
        '{', 99,
        '\t', 66,
        ' ', 66,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0) ADVANCE(101);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(45);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '{') ADVANCE(99);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead != 0) ADVANCE(101);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '{') ADVANCE(101);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'A') ADVANCE(75);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'A') ADVANCE(74);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'A') ADVANCE(96);
      if (lookahead == 'O') ADVANCE(93);
      if (lookahead == 'U') ADVANCE(94);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'C') ADVANCE(94);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'C') ADVANCE(82);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'C') ADVANCE(76);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'D') ADVANCE(56);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'E') ADVANCE(56);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'E') ADVANCE(84);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'E') ADVANCE(94);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'E') ADVANCE(69);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'E') ADVANCE(72);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'E') ADVANCE(97);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'H') ADVANCE(56);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'I') ADVANCE(89);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'L') ADVANCE(81);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'N') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'N') ADVANCE(92);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'N') ADVANCE(80);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'O') ADVANCE(85);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'O') ADVANCE(86);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'P') ADVANCE(95);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'R') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'S') ADVANCE(56);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'S') ADVANCE(94);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'T') ADVANCE(56);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'T') ADVANCE(83);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'T') ADVANCE(73);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == 'T') ADVANCE(76);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(65);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '{') ADVANCE(37);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_text);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < 'a' || '{' < lookahead)) ADVANCE(101);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '{') ADVANCE(101);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_variable);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 41},
  [2] = {.lex_state = 41},
  [3] = {.lex_state = 41},
  [4] = {.lex_state = 41},
  [5] = {.lex_state = 42},
  [6] = {.lex_state = 42},
  [7] = {.lex_state = 43},
  [8] = {.lex_state = 43},
  [9] = {.lex_state = 36},
  [10] = {.lex_state = 43},
  [11] = {.lex_state = 43},
  [12] = {.lex_state = 43},
  [13] = {.lex_state = 43},
  [14] = {.lex_state = 43},
  [15] = {.lex_state = 43},
  [16] = {.lex_state = 43},
  [17] = {.lex_state = 43},
  [18] = {.lex_state = 43},
  [19] = {.lex_state = 43},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym_separator] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_variable_name] = ACTIONS(1),
    [sym_method] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [sym_version] = ACTIONS(1),
    [sym_header_name] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(25),
    [sym__line] = STATE(21),
    [sym_variable_declaration] = STATE(21),
    [sym_request_line] = STATE(21),
    [sym_header] = STATE(21),
    [sym_body_line] = STATE(21),
    [aux_sym__text] = STATE(10),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_separator] = ACTIONS(7),
    [sym_comment] = ACTIONS(7),
    [sym_variable_name] = ACTIONS(9),
    [sym_method] = ACTIONS(11),
    [sym_header_name] = ACTIONS(13),
    [sym_text] = ACTIONS(15),
    [sym_variable] = ACTIONS(15),
  },
  [STATE(2)] = {
    [sym__line] = STATE(23),
    [sym_variable_declaration] = STATE(23),
    [sym_request_line] = STATE(23),
    [sym_header] = STATE(23),
    [sym_body_line] = STATE(23),
    [aux_sym__text] = STATE(10),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym__newline] = ACTIONS(19),
    [sym_separator] = ACTIONS(21),
    [sym_comment] = ACTIONS(21),
    [sym_variable_name] = ACTIONS(9),
    [sym_method] = ACTIONS(11),
    [sym_header_name] = ACTIONS(13),
    [sym_text] = ACTIONS(15),
    [sym_variable] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym__line] = STATE(26),
    [sym_variable_declaration] = STATE(26),
    [sym_request_line] = STATE(26),
    [sym_header] = STATE(26),
    [sym_body_line] = STATE(26),
    [aux_sym__text] = STATE(16),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym__newline] = ACTIONS(25),
    [sym_separator] = ACTIONS(28),
    [sym_comment] = ACTIONS(28),
    [sym_variable_name] = ACTIONS(31),
    [sym_method] = ACTIONS(34),
    [sym_header_name] = ACTIONS(37),
    [sym_text] = ACTIONS(40),
    [sym_variable] = ACTIONS(40),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 8,
      sym__newline,
      sym_separator,
      sym_comment,
      sym_variable_name,
      sym_method,
      sym_header_name,
      sym_text,
      sym_variable,
  [14] = 4,
    ACTIONS(49), 1,
      sym_variable,
    STATE(6), 1,
      aux_sym_url_repeat1,
    ACTIONS(47), 2,
      aux_sym_url_token1,
      anon_sym_LBRACE,
    ACTIONS(45), 3,
      ts_builtin_sym_end,
      sym__newline,
      sym_version,
  [30] = 4,
    ACTIONS(56), 1,
      sym_variable,
    STATE(6), 1,
      aux_sym_url_repeat1,
    ACTIONS(53), 2,
      aux_sym_url_token1,
      anon_sym_LBRACE,
    ACTIONS(51), 3,
      ts_builtin_sym_end,
      sym__newline,
      sym_version,
  [46] = 4,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    ACTIONS(61), 1,
      sym__newline,
    STATE(11), 1,
      aux_sym__text,
    ACTIONS(63), 2,
      sym_text,
      sym_variable,
  [60] = 4,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    ACTIONS(67), 1,
      sym__newline,
    STATE(13), 1,
      aux_sym__text,
    ACTIONS(69), 2,
      sym_text,
      sym_variable,
  [74] = 4,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    STATE(5), 1,
      aux_sym_url_repeat1,
    STATE(20), 1,
      sym_url,
    ACTIONS(71), 2,
      aux_sym_url_token1,
      sym_variable,
  [88] = 4,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    ACTIONS(77), 1,
      sym__newline,
    STATE(12), 1,
      aux_sym__text,
    ACTIONS(79), 2,
      sym_text,
      sym_variable,
  [102] = 4,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    ACTIONS(83), 1,
      sym__newline,
    STATE(12), 1,
      aux_sym__text,
    ACTIONS(79), 2,
      sym_text,
      sym_variable,
  [116] = 4,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    ACTIONS(87), 1,
      sym__newline,
    STATE(12), 1,
      aux_sym__text,
    ACTIONS(89), 2,
      sym_text,
      sym_variable,
  [130] = 4,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    ACTIONS(94), 1,
      sym__newline,
    STATE(12), 1,
      aux_sym__text,
    ACTIONS(79), 2,
      sym_text,
      sym_variable,
  [144] = 3,
    ACTIONS(87), 1,
      sym__newline,
    STATE(14), 1,
      aux_sym__text,
    ACTIONS(96), 2,
      sym_text,
      sym_variable,
  [155] = 3,
    ACTIONS(83), 1,
      sym__newline,
    STATE(14), 1,
      aux_sym__text,
    ACTIONS(99), 2,
      sym_text,
      sym_variable,
  [166] = 3,
    ACTIONS(77), 1,
      sym__newline,
    STATE(14), 1,
      aux_sym__text,
    ACTIONS(99), 2,
      sym_text,
      sym_variable,
  [177] = 3,
    ACTIONS(61), 1,
      sym__newline,
    STATE(15), 1,
      aux_sym__text,
    ACTIONS(101), 2,
      sym_text,
      sym_variable,
  [188] = 3,
    ACTIONS(94), 1,
      sym__newline,
    STATE(14), 1,
      aux_sym__text,
    ACTIONS(99), 2,
      sym_text,
      sym_variable,
  [199] = 3,
    ACTIONS(67), 1,
      sym__newline,
    STATE(18), 1,
      aux_sym__text,
    ACTIONS(103), 2,
      sym_text,
      sym_variable,
  [210] = 2,
    ACTIONS(107), 1,
      sym_version,
    ACTIONS(105), 2,
      ts_builtin_sym_end,
      sym__newline,
  [218] = 2,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(109), 1,
      sym__newline,
  [225] = 1,
    ACTIONS(111), 2,
      ts_builtin_sym_end,
      sym__newline,
  [230] = 2,
    ACTIONS(109), 1,
      sym__newline,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
  [237] = 1,
    ACTIONS(115), 1,
      anon_sym_EQ,
  [241] = 1,
    ACTIONS(117), 1,
      ts_builtin_sym_end,
  [245] = 1,
    ACTIONS(109), 1,
      sym__newline,
  [249] = 1,
    ACTIONS(119), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 14,
  [SMALL_STATE(6)] = 30,
  [SMALL_STATE(7)] = 46,
  [SMALL_STATE(8)] = 60,
  [SMALL_STATE(9)] = 74,
  [SMALL_STATE(10)] = 88,
  [SMALL_STATE(11)] = 102,
  [SMALL_STATE(12)] = 116,
  [SMALL_STATE(13)] = 130,
  [SMALL_STATE(14)] = 144,
  [SMALL_STATE(15)] = 155,
  [SMALL_STATE(16)] = 166,
  [SMALL_STATE(17)] = 177,
  [SMALL_STATE(18)] = 188,
  [SMALL_STATE(19)] = 199,
  [SMALL_STATE(20)] = 210,
  [SMALL_STATE(21)] = 218,
  [SMALL_STATE(22)] = 225,
  [SMALL_STATE(23)] = 230,
  [SMALL_STATE(24)] = 237,
  [SMALL_STATE(25)] = 241,
  [SMALL_STATE(26)] = 245,
  [SMALL_STATE(27)] = 249,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_url, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_url_repeat1, 2, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_url_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_url_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 1, 0, 1),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 1, 0, 1),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 2, 0, 1),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 2, 0, 1),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_line, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body_line, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 2, 0, 3),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 2, 0, 3),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__text, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__text, 2, 0, 0),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__text, 2, 0, 0), SHIFT_REPEAT(12),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 3, 0, 4),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 3, 0, 4),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__text, 2, 0, 0), SHIFT_REPEAT(14),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_line, 2, 0, 2),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_line, 3, 0, 5),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [117] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_http(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
