/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 53
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 12
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_header = 1,
  sym_comment = 2,
  anon_sym_Project = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_EQ = 6,
  anon_sym_COMMA = 7,
  anon_sym_EndProject = 8,
  anon_sym_Global = 9,
  anon_sym_EndGlobal = 10,
  anon_sym_ProjectSection = 11,
  anon_sym_GlobalSection = 12,
  anon_sym_EndProjectSection = 13,
  anon_sym_EndGlobalSection = 14,
  sym_section_name = 15,
  anon_sym_preProject = 16,
  anon_sym_postProject = 17,
  anon_sym_preSolution = 18,
  anon_sym_postSolution = 19,
  sym_key = 20,
  sym_value = 21,
  sym_string = 22,
  sym_document = 23,
  sym__item = 24,
  sym_project = 25,
  sym_global = 26,
  sym_section = 27,
  sym_timing = 28,
  sym_assignment = 29,
  aux_sym_document_repeat1 = 30,
  aux_sym_project_repeat1 = 31,
  aux_sym_global_repeat1 = 32,
  aux_sym_section_repeat1 = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_header] = "header",
  [sym_comment] = "comment",
  [anon_sym_Project] = "Project",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [anon_sym_EndProject] = "EndProject",
  [anon_sym_Global] = "Global",
  [anon_sym_EndGlobal] = "EndGlobal",
  [anon_sym_ProjectSection] = "ProjectSection",
  [anon_sym_GlobalSection] = "GlobalSection",
  [anon_sym_EndProjectSection] = "EndProjectSection",
  [anon_sym_EndGlobalSection] = "EndGlobalSection",
  [sym_section_name] = "section_name",
  [anon_sym_preProject] = "preProject",
  [anon_sym_postProject] = "postProject",
  [anon_sym_preSolution] = "preSolution",
  [anon_sym_postSolution] = "postSolution",
  [sym_key] = "key",
  [sym_value] = "value",
  [sym_string] = "string",
  [sym_document] = "document",
  [sym__item] = "_item",
  [sym_project] = "project",
  [sym_global] = "global",
  [sym_section] = "section",
  [sym_timing] = "timing",
  [sym_assignment] = "assignment",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_project_repeat1] = "project_repeat1",
  [aux_sym_global_repeat1] = "global_repeat1",
  [aux_sym_section_repeat1] = "section_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_header] = sym_header,
  [sym_comment] = sym_comment,
  [anon_sym_Project] = anon_sym_Project,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_EndProject] = anon_sym_EndProject,
  [anon_sym_Global] = anon_sym_Global,
  [anon_sym_EndGlobal] = anon_sym_EndGlobal,
  [anon_sym_ProjectSection] = anon_sym_ProjectSection,
  [anon_sym_GlobalSection] = anon_sym_GlobalSection,
  [anon_sym_EndProjectSection] = anon_sym_EndProjectSection,
  [anon_sym_EndGlobalSection] = anon_sym_EndGlobalSection,
  [sym_section_name] = sym_section_name,
  [anon_sym_preProject] = anon_sym_preProject,
  [anon_sym_postProject] = anon_sym_postProject,
  [anon_sym_preSolution] = anon_sym_preSolution,
  [anon_sym_postSolution] = anon_sym_postSolution,
  [sym_key] = sym_key,
  [sym_value] = sym_value,
  [sym_string] = sym_string,
  [sym_document] = sym_document,
  [sym__item] = sym__item,
  [sym_project] = sym_project,
  [sym_global] = sym_global,
  [sym_section] = sym_section,
  [sym_timing] = sym_timing,
  [sym_assignment] = sym_assignment,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_project_repeat1] = aux_sym_project_repeat1,
  [aux_sym_global_repeat1] = aux_sym_global_repeat1,
  [aux_sym_section_repeat1] = aux_sym_section_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_Project] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EndProject] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Global] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EndGlobal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ProjectSection] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GlobalSection] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EndProjectSection] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EndGlobalSection] = {
    .visible = true,
    .named = false,
  },
  [sym_section_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_preProject] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_postProject] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_preSolution] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_postSolution] = {
    .visible = true,
    .named = false,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_project] = {
    .visible = true,
    .named = true,
  },
  [sym_global] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_timing] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_project_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_global_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_guid = 1,
  field_key = 2,
  field_name = 3,
  field_path = 4,
  field_type = 5,
  field_value = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_guid] = "guid",
  [field_key] = "key",
  [field_name] = "name",
  [field_path] = "path",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_value, 2},
  [2] =
    {field_name, 2},
  [3] =
    {field_guid, 9},
    {field_name, 5},
    {field_path, 7},
    {field_type, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 16,
  [19] = 19,
  [20] = 17,
  [21] = 15,
  [22] = 22,
  [23] = 8,
  [24] = 24,
  [25] = 25,
  [26] = 24,
  [27] = 8,
  [28] = 22,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 29,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 29,
  [46] = 32,
  [47] = 47,
  [48] = 32,
  [49] = 37,
  [50] = 35,
  [51] = 47,
  [52] = 33,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(73);
      ADVANCE_MAP(
        '"', 1,
        '#', 77,
        '(', 80,
        ')', 81,
        ',', 83,
        '=', 82,
        'E', 127,
        'G', 121,
        'P', 145,
        'p', 132,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(277);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == 'E') ADVANCE(43);
      if (lookahead == 'G') ADVANCE(34);
      if (lookahead == 'P') ADVANCE(56);
      if (lookahead == 'p') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == 'E') ADVANCE(235);
      if (lookahead == 'G') ADVANCE(228);
      if (lookahead == 'P') ADVANCE(256);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (lookahead != 0 &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 4:
      if (lookahead == 'E') ADVANCE(236);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (lookahead != 0 &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 5:
      if (lookahead == 'G') ADVANCE(38);
      END_STATE();
    case 6:
      if (lookahead == 'P') ADVANCE(57);
      if (lookahead == 'S') ADVANCE(49);
      END_STATE();
    case 7:
      if (lookahead == 'P') ADVANCE(58);
      if (lookahead == 'S') ADVANCE(54);
      END_STATE();
    case 8:
      if (lookahead == 'S') ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead == 'S') ADVANCE(25);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(35);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(33);
      END_STATE();
    case 12:
      if (lookahead == 'b') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == 'b') ADVANCE(11);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(67);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(60);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(61);
      END_STATE();
    case 17:
      if (lookahead == 'c') ADVANCE(64);
      END_STATE();
    case 18:
      if (lookahead == 'c') ADVANCE(65);
      END_STATE();
    case 19:
      if (lookahead == 'd') ADVANCE(5);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(47);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(48);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(50);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(51);
      END_STATE();
    case 30:
      if (lookahead == 'j') ADVANCE(21);
      END_STATE();
    case 31:
      if (lookahead == 'j') ADVANCE(23);
      END_STATE();
    case 32:
      if (lookahead == 'j') ADVANCE(24);
      END_STATE();
    case 33:
      if (lookahead == 'l') ADVANCE(87);
      END_STATE();
    case 34:
      if (lookahead == 'l') ADVANCE(45);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 36:
      if (lookahead == 'l') ADVANCE(68);
      END_STATE();
    case 37:
      if (lookahead == 'l') ADVANCE(69);
      END_STATE();
    case 38:
      if (lookahead == 'l') ADVANCE(52);
      END_STATE();
    case 39:
      if (lookahead == 'n') ADVANCE(164);
      END_STATE();
    case 40:
      if (lookahead == 'n') ADVANCE(165);
      END_STATE();
    case 41:
      if (lookahead == 'n') ADVANCE(89);
      END_STATE();
    case 42:
      if (lookahead == 'n') ADVANCE(88);
      END_STATE();
    case 43:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 44:
      if (lookahead == 'o') ADVANCE(59);
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 45:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 46:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 47:
      if (lookahead == 'o') ADVANCE(39);
      END_STATE();
    case 48:
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 49:
      if (lookahead == 'o') ADVANCE(36);
      END_STATE();
    case 50:
      if (lookahead == 'o') ADVANCE(41);
      END_STATE();
    case 51:
      if (lookahead == 'o') ADVANCE(42);
      END_STATE();
    case 52:
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 53:
      if (lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 54:
      if (lookahead == 'o') ADVANCE(37);
      END_STATE();
    case 55:
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 56:
      if (lookahead == 'r') ADVANCE(46);
      END_STATE();
    case 57:
      if (lookahead == 'r') ADVANCE(53);
      END_STATE();
    case 58:
      if (lookahead == 'r') ADVANCE(55);
      END_STATE();
    case 59:
      if (lookahead == 's') ADVANCE(66);
      END_STATE();
    case 60:
      if (lookahead == 't') ADVANCE(162);
      END_STATE();
    case 61:
      if (lookahead == 't') ADVANCE(163);
      END_STATE();
    case 62:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 63:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 64:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 65:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 66:
      if (lookahead == 't') ADVANCE(7);
      END_STATE();
    case 67:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 68:
      if (lookahead == 'u') ADVANCE(62);
      END_STATE();
    case 69:
      if (lookahead == 'u') ADVANCE(63);
      END_STATE();
    case 70:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(70);
      if (lookahead != 0) ADVANCE(276);
      END_STATE();
    case 71:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(71);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 72:
      if (eof) ADVANCE(73);
      if (lookahead == '#') ADVANCE(76);
      if (lookahead == 'G') ADVANCE(222);
      if (lookahead == 'M') ADVANCE(209);
      if (lookahead == 'P') ADVANCE(254);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(72);
      if (lookahead != 0 &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_header);
      if (lookahead == '=') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_header);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '=') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_Project);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_Project);
      if (lookahead == 'S') ADVANCE(112);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_EndProject);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_Global);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_Global);
      if (lookahead == 'S') ADVANCE(109);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_EndGlobal);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_ProjectSection);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_GlobalSection);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_EndProjectSection);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_EndGlobalSection);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'G') ADVANCE(126);
      if (lookahead == 'P') ADVANCE(146);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'P') ADVANCE(147);
      if (lookahead == 'S') ADVANCE(137);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'P') ADVANCE(148);
      if (lookahead == 'S') ADVANCE(142);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'a') ADVANCE(122);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'a') ADVANCE(124);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'b') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'b') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'c') ADVANCE(150);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'c') ADVANCE(152);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'c') ADVANCE(153);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'c') ADVANCE(154);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'c') ADVANCE(156);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'c') ADVANCE(157);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'd') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'e') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'e') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'e') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'e') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'e') ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'e') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'e') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'i') ADVANCE(135);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'i') ADVANCE(136);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'i') ADVANCE(138);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'i') ADVANCE(139);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'j') ADVANCE(107);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'j') ADVANCE(108);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'j') ADVANCE(110);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'j') ADVANCE(111);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'l') ADVANCE(133);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'l') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'l') ADVANCE(159);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'l') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'l') ADVANCE(160);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'l') ADVANCE(140);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'n') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'n') ADVANCE(164);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'n') ADVANCE(165);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'n') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'n') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'o') ADVANCE(149);
      if (lookahead == 'r') ADVANCE(106);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'o') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'o') ADVANCE(117);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'o') ADVANCE(128);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'o') ADVANCE(129);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'o') ADVANCE(123);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'o') ADVANCE(130);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'o') ADVANCE(131);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'o') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'o') ADVANCE(118);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'o') ADVANCE(125);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'o') ADVANCE(119);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'o') ADVANCE(120);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'r') ADVANCE(134);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'r') ADVANCE(141);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'r') ADVANCE(143);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'r') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 's') ADVANCE(158);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 't') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 't') ADVANCE(113);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 't') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 't') ADVANCE(162);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 't') ADVANCE(163);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 't') ADVANCE(114);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 't') ADVANCE(115);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 't') ADVANCE(116);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 't') ADVANCE(94);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'u') ADVANCE(151);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_section_name);
      if (lookahead == 'u') ADVANCE(155);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_section_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(161);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(anon_sym_preProject);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(anon_sym_postProject);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(anon_sym_preSolution);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(anon_sym_postSolution);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == ' ') ADVANCE(179);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == ' ') ADVANCE(173);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == ' ') ADVANCE(170);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == ' ') ADVANCE(174);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'F') ADVANCE(211);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'G') ADVANCE(229);
      if (lookahead == 'P') ADVANCE(258);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'P') ADVANCE(257);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'S') ADVANCE(264);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'S') ADVANCE(245);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'S') ADVANCE(203);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'S') ADVANCE(204);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'S') ADVANCE(205);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'S') ADVANCE(206);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'V') ADVANCE(210);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'a') ADVANCE(223);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'a') ADVANCE(225);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'a') ADVANCE(227);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'a') ADVANCE(230);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'b') ADVANCE(180);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'b') ADVANCE(182);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'b') ADVANCE(183);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'c') ADVANCE(262);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'c') ADVANCE(270);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'c') ADVANCE(261);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'c') ADVANCE(255);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'c') ADVANCE(266);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'c') ADVANCE(267);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'c') ADVANCE(268);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'c') ADVANCE(269);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'c') ADVANCE(271);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'd') ADVANCE(172);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'd') ADVANCE(171);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'd') ADVANCE(212);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'e') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'e') ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'e') ADVANCE(188);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'e') ADVANCE(189);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 203:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'e') ADVANCE(191);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'e') ADVANCE(192);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'e') ADVANCE(193);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'e') ADVANCE(194);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'e') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 208:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'f') ADVANCE(263);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 209:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'i') ADVANCE(190);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 210:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'i') ADVANCE(259);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 211:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'i') ADVANCE(224);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 212:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'i') ADVANCE(243);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 213:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'i') ADVANCE(242);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 214:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'i') ADVANCE(244);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 215:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'i') ADVANCE(246);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 216:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'i') ADVANCE(247);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 217:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'i') ADVANCE(248);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 218:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'j') ADVANCE(200);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 219:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'j') ADVANCE(201);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 220:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'j') ADVANCE(202);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 221:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'j') ADVANCE(207);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 222:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'l') ADVANCE(238);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 223:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'l') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 224:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'l') ADVANCE(199);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 225:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'l') ADVANCE(167);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 226:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'l') ADVANCE(273);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 227:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'l') ADVANCE(175);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 228:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'l') ADVANCE(249);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 229:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'l') ADVANCE(252);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 230:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'l') ADVANCE(177);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 231:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'n') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 232:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'n') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 233:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'n') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 234:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'n') ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 235:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'n') ADVANCE(196);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 236:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'n') ADVANCE(197);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 237:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'n') ADVANCE(168);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 238:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'o') ADVANCE(184);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 239:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'o') ADVANCE(218);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 240:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'o') ADVANCE(260);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 241:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'o') ADVANCE(208);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 242:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'o') ADVANCE(237);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 243:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'o') ADVANCE(169);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 244:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'o') ADVANCE(231);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 245:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'o') ADVANCE(226);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 246:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'o') ADVANCE(232);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 247:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'o') ADVANCE(233);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 248:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'o') ADVANCE(234);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 249:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'o') ADVANCE(185);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 250:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'o') ADVANCE(219);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 251:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'o') ADVANCE(220);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 252:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'o') ADVANCE(186);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 253:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'o') ADVANCE(221);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 254:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'r') ADVANCE(239);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 255:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'r') ADVANCE(240);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 256:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'r') ADVANCE(250);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 257:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'r') ADVANCE(251);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 258:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'r') ADVANCE(253);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 259:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 's') ADVANCE(274);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 260:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 's') ADVANCE(241);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 261:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 't') ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 262:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 't') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 263:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 't') ADVANCE(166);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 264:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 't') ADVANCE(272);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 265:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 't') ADVANCE(213);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 266:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 't') ADVANCE(214);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 267:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 't') ADVANCE(215);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 268:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 't') ADVANCE(216);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 269:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 't') ADVANCE(217);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 270:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 't') ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 271:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 't') ADVANCE(178);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 272:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'u') ADVANCE(198);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 273:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'u') ADVANCE(265);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 274:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == 'u') ADVANCE(181);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 275:
      ACCEPT_TOKEN(sym_key);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(275);
      END_STATE();
    case 276:
      ACCEPT_TOKEN(sym_value);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(276);
      END_STATE();
    case 277:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 72},
  [2] = {.lex_state = 72},
  [3] = {.lex_state = 72},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 72},
  [8] = {.lex_state = 72},
  [9] = {.lex_state = 72},
  [10] = {.lex_state = 72},
  [11] = {.lex_state = 72},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 70},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 70},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 70},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 71},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 71},
  [52] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_Project] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_EndProject] = ACTIONS(1),
    [anon_sym_Global] = ACTIONS(1),
    [anon_sym_EndGlobal] = ACTIONS(1),
    [anon_sym_ProjectSection] = ACTIONS(1),
    [anon_sym_GlobalSection] = ACTIONS(1),
    [sym_section_name] = ACTIONS(1),
    [anon_sym_preProject] = ACTIONS(1),
    [anon_sym_postProject] = ACTIONS(1),
    [anon_sym_preSolution] = ACTIONS(1),
    [anon_sym_postSolution] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(39),
    [sym__item] = STATE(2),
    [sym_project] = STATE(2),
    [sym_global] = STATE(2),
    [sym_assignment] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_header] = ACTIONS(5),
    [sym_comment] = ACTIONS(5),
    [anon_sym_Project] = ACTIONS(7),
    [anon_sym_Global] = ACTIONS(9),
    [sym_key] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(7), 1,
      anon_sym_Project,
    ACTIONS(9), 1,
      anon_sym_Global,
    ACTIONS(11), 1,
      sym_key,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 2,
      sym_header,
      sym_comment,
    STATE(3), 5,
      sym__item,
      sym_project,
      sym_global,
      sym_assignment,
      aux_sym_document_repeat1,
  [24] = 6,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(22), 1,
      anon_sym_Project,
    ACTIONS(25), 1,
      anon_sym_Global,
    ACTIONS(28), 1,
      sym_key,
    ACTIONS(19), 2,
      sym_header,
      sym_comment,
    STATE(3), 5,
      sym__item,
      sym_project,
      sym_global,
      sym_assignment,
      aux_sym_document_repeat1,
  [48] = 4,
    ACTIONS(31), 1,
      anon_sym_EndProject,
    ACTIONS(36), 1,
      sym_key,
    ACTIONS(33), 2,
      anon_sym_ProjectSection,
      anon_sym_GlobalSection,
    STATE(4), 3,
      sym_section,
      sym_assignment,
      aux_sym_project_repeat1,
  [64] = 4,
    ACTIONS(39), 1,
      anon_sym_EndProject,
    ACTIONS(43), 1,
      sym_key,
    ACTIONS(41), 2,
      anon_sym_ProjectSection,
      anon_sym_GlobalSection,
    STATE(6), 3,
      sym_section,
      sym_assignment,
      aux_sym_project_repeat1,
  [80] = 4,
    ACTIONS(43), 1,
      sym_key,
    ACTIONS(45), 1,
      anon_sym_EndProject,
    ACTIONS(41), 2,
      anon_sym_ProjectSection,
      anon_sym_GlobalSection,
    STATE(4), 3,
      sym_section,
      sym_assignment,
      aux_sym_project_repeat1,
  [96] = 2,
    ACTIONS(49), 1,
      sym_key,
    ACTIONS(47), 5,
      ts_builtin_sym_end,
      sym_header,
      sym_comment,
      anon_sym_Project,
      anon_sym_Global,
  [107] = 2,
    ACTIONS(53), 1,
      sym_key,
    ACTIONS(51), 5,
      ts_builtin_sym_end,
      sym_header,
      sym_comment,
      anon_sym_Project,
      anon_sym_Global,
  [118] = 2,
    ACTIONS(57), 1,
      sym_key,
    ACTIONS(55), 5,
      ts_builtin_sym_end,
      sym_header,
      sym_comment,
      anon_sym_Project,
      anon_sym_Global,
  [129] = 2,
    ACTIONS(61), 1,
      sym_key,
    ACTIONS(59), 5,
      ts_builtin_sym_end,
      sym_header,
      sym_comment,
      anon_sym_Project,
      anon_sym_Global,
  [140] = 2,
    ACTIONS(65), 1,
      sym_key,
    ACTIONS(63), 5,
      ts_builtin_sym_end,
      sym_header,
      sym_comment,
      anon_sym_Project,
      anon_sym_Global,
  [151] = 3,
    ACTIONS(67), 1,
      anon_sym_EndGlobal,
    ACTIONS(69), 2,
      anon_sym_ProjectSection,
      anon_sym_GlobalSection,
    STATE(13), 2,
      sym_section,
      aux_sym_global_repeat1,
  [163] = 3,
    ACTIONS(71), 1,
      anon_sym_EndGlobal,
    ACTIONS(69), 2,
      anon_sym_ProjectSection,
      anon_sym_GlobalSection,
    STATE(14), 2,
      sym_section,
      aux_sym_global_repeat1,
  [175] = 3,
    ACTIONS(73), 1,
      anon_sym_EndGlobal,
    ACTIONS(75), 2,
      anon_sym_ProjectSection,
      anon_sym_GlobalSection,
    STATE(14), 2,
      sym_section,
      aux_sym_global_repeat1,
  [187] = 2,
    STATE(16), 1,
      sym_timing,
    ACTIONS(78), 4,
      anon_sym_preProject,
      anon_sym_postProject,
      anon_sym_preSolution,
      anon_sym_postSolution,
  [197] = 3,
    ACTIONS(82), 1,
      sym_key,
    ACTIONS(80), 2,
      anon_sym_EndProjectSection,
      anon_sym_EndGlobalSection,
    STATE(17), 2,
      sym_assignment,
      aux_sym_section_repeat1,
  [209] = 3,
    ACTIONS(82), 1,
      sym_key,
    ACTIONS(84), 2,
      anon_sym_EndProjectSection,
      anon_sym_EndGlobalSection,
    STATE(19), 2,
      sym_assignment,
      aux_sym_section_repeat1,
  [221] = 3,
    ACTIONS(82), 1,
      sym_key,
    ACTIONS(86), 2,
      anon_sym_EndProjectSection,
      anon_sym_EndGlobalSection,
    STATE(20), 2,
      sym_assignment,
      aux_sym_section_repeat1,
  [233] = 3,
    ACTIONS(90), 1,
      sym_key,
    ACTIONS(88), 2,
      anon_sym_EndProjectSection,
      anon_sym_EndGlobalSection,
    STATE(19), 2,
      sym_assignment,
      aux_sym_section_repeat1,
  [245] = 3,
    ACTIONS(82), 1,
      sym_key,
    ACTIONS(93), 2,
      anon_sym_EndProjectSection,
      anon_sym_EndGlobalSection,
    STATE(19), 2,
      sym_assignment,
      aux_sym_section_repeat1,
  [257] = 2,
    STATE(18), 1,
      sym_timing,
    ACTIONS(78), 4,
      anon_sym_preProject,
      anon_sym_postProject,
      anon_sym_preSolution,
      anon_sym_postSolution,
  [267] = 2,
    ACTIONS(97), 1,
      sym_key,
    ACTIONS(95), 3,
      anon_sym_EndProject,
      anon_sym_ProjectSection,
      anon_sym_GlobalSection,
  [276] = 2,
    ACTIONS(53), 1,
      sym_key,
    ACTIONS(51), 3,
      anon_sym_EndProject,
      anon_sym_ProjectSection,
      anon_sym_GlobalSection,
  [285] = 2,
    ACTIONS(101), 1,
      sym_key,
    ACTIONS(99), 3,
      anon_sym_EndProject,
      anon_sym_ProjectSection,
      anon_sym_GlobalSection,
  [294] = 2,
    ACTIONS(105), 1,
      sym_key,
    ACTIONS(103), 2,
      anon_sym_EndProjectSection,
      anon_sym_EndGlobalSection,
  [302] = 1,
    ACTIONS(99), 3,
      anon_sym_EndGlobal,
      anon_sym_ProjectSection,
      anon_sym_GlobalSection,
  [308] = 2,
    ACTIONS(53), 1,
      sym_key,
    ACTIONS(51), 2,
      anon_sym_EndProjectSection,
      anon_sym_EndGlobalSection,
  [316] = 1,
    ACTIONS(95), 3,
      anon_sym_EndGlobal,
      anon_sym_ProjectSection,
      anon_sym_GlobalSection,
  [322] = 1,
    ACTIONS(107), 1,
      sym_value,
  [326] = 1,
    ACTIONS(109), 1,
      sym_string,
  [330] = 1,
    ACTIONS(111), 1,
      sym_string,
  [334] = 1,
    ACTIONS(113), 1,
      anon_sym_EQ,
  [338] = 1,
    ACTIONS(115), 1,
      anon_sym_LPAREN,
  [342] = 1,
    ACTIONS(117), 1,
      anon_sym_EQ,
  [346] = 1,
    ACTIONS(119), 1,
      anon_sym_RPAREN,
  [350] = 1,
    ACTIONS(121), 1,
      sym_string,
  [354] = 1,
    ACTIONS(123), 1,
      anon_sym_EQ,
  [358] = 1,
    ACTIONS(125), 1,
      anon_sym_COMMA,
  [362] = 1,
    ACTIONS(127), 1,
      ts_builtin_sym_end,
  [366] = 1,
    ACTIONS(129), 1,
      sym_string,
  [370] = 1,
    ACTIONS(131), 1,
      sym_value,
  [374] = 1,
    ACTIONS(133), 1,
      anon_sym_LPAREN,
  [378] = 1,
    ACTIONS(135), 1,
      anon_sym_COMMA,
  [382] = 1,
    ACTIONS(137), 1,
      anon_sym_RPAREN,
  [386] = 1,
    ACTIONS(139), 1,
      sym_value,
  [390] = 1,
    ACTIONS(141), 1,
      anon_sym_EQ,
  [394] = 1,
    ACTIONS(143), 1,
      sym_section_name,
  [398] = 1,
    ACTIONS(145), 1,
      anon_sym_EQ,
  [402] = 1,
    ACTIONS(147), 1,
      anon_sym_EQ,
  [406] = 1,
    ACTIONS(149), 1,
      anon_sym_RPAREN,
  [410] = 1,
    ACTIONS(151), 1,
      sym_section_name,
  [414] = 1,
    ACTIONS(153), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 24,
  [SMALL_STATE(4)] = 48,
  [SMALL_STATE(5)] = 64,
  [SMALL_STATE(6)] = 80,
  [SMALL_STATE(7)] = 96,
  [SMALL_STATE(8)] = 107,
  [SMALL_STATE(9)] = 118,
  [SMALL_STATE(10)] = 129,
  [SMALL_STATE(11)] = 140,
  [SMALL_STATE(12)] = 151,
  [SMALL_STATE(13)] = 163,
  [SMALL_STATE(14)] = 175,
  [SMALL_STATE(15)] = 187,
  [SMALL_STATE(16)] = 197,
  [SMALL_STATE(17)] = 209,
  [SMALL_STATE(18)] = 221,
  [SMALL_STATE(19)] = 233,
  [SMALL_STATE(20)] = 245,
  [SMALL_STATE(21)] = 257,
  [SMALL_STATE(22)] = 267,
  [SMALL_STATE(23)] = 276,
  [SMALL_STATE(24)] = 285,
  [SMALL_STATE(25)] = 294,
  [SMALL_STATE(26)] = 302,
  [SMALL_STATE(27)] = 308,
  [SMALL_STATE(28)] = 316,
  [SMALL_STATE(29)] = 322,
  [SMALL_STATE(30)] = 326,
  [SMALL_STATE(31)] = 330,
  [SMALL_STATE(32)] = 334,
  [SMALL_STATE(33)] = 338,
  [SMALL_STATE(34)] = 342,
  [SMALL_STATE(35)] = 346,
  [SMALL_STATE(36)] = 350,
  [SMALL_STATE(37)] = 354,
  [SMALL_STATE(38)] = 358,
  [SMALL_STATE(39)] = 362,
  [SMALL_STATE(40)] = 366,
  [SMALL_STATE(41)] = 370,
  [SMALL_STATE(42)] = 374,
  [SMALL_STATE(43)] = 378,
  [SMALL_STATE(44)] = 382,
  [SMALL_STATE(45)] = 386,
  [SMALL_STATE(46)] = 390,
  [SMALL_STATE(47)] = 394,
  [SMALL_STATE(48)] = 398,
  [SMALL_STATE(49)] = 402,
  [SMALL_STATE(50)] = 406,
  [SMALL_STATE(51)] = 410,
  [SMALL_STATE(52)] = 414,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_project_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_project_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_project_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_global, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 1),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 1),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_global, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_project, 11, 0, 3),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_project, 11, 0, 3),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_project, 12, 0, 3),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_project, 12, 0, 3),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_global_repeat1, 2, 0, 0),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_global_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 8, 0, 2),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 8, 0, 2),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 7, 0, 2),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 7, 0, 2),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_timing, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_timing, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [127] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sln(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
